# Generated by Django 5.0 on 2023-12-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItsyMessage',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('messageContent', models.CharField(max_length=10000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
